# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FS2C8mPT5np5dbfAkvIiazXUyaphUEIB
"""

class Cliente:
    def __init__(self, nombre, apellido, cedula, email, vip, direccion, telefono, celular, edad):
        self.__nombre = nombre
        self.__apellido = apellido
        self.cedula = cedula        # usa setter (valida)
        self.__email = email
        self.__vip = vip
        self.__direccion = direccion
        self.__telefono = telefono
        self.__celular = celular
        self.edad = edad            # usa setter (valida)

    # Nombre
    @property
    def nombre(self):
        return self.__nombre

    @nombre.setter
    def nombre(self, valor):
        self.__nombre = valor

    # Apellido
    @property
    def apellido(self):
        return self.__apellido

    @apellido.setter
    def apellido(self, valor):
        self.__apellido = valor

    # Cédula (validación: 10 dígitos)
    @property
    def cedula(self):
        return self.__cedula

    @cedula.setter
    def cedula(self, valor):
        if isinstance(valor, str) and valor.isdigit() and len(valor) == 10:
            self.__cedula = valor
        else:
            raise ValueError("La cédula debe tener exactamente 10 dígitos numéricos")

    # Email
    @property
    def email(self):
        return self.__email

    @email.setter
    def email(self, valor):
        self.__email = valor

    # VIP
    @property
    def vip(self):
        return self.__vip

    @vip.setter
    def vip(self, valor):
        self.__vip = valor

    # Dirección
    @property
    def direccion(self):
        return self.__direccion

    @direccion.setter
    def direccion(self, valor):
        self.__direccion = valor

    # Teléfono
    @property
    def telefono(self):
        return self.__telefono

    @telefono.setter
    def telefono(self, valor):
        self.__telefono = valor

    # Celular
    @property
    def celular(self):
        return self.__celular

    @celular.setter
    def celular(self, valor):
        self.__celular = valor

    # Edad (validación: mayor a 18)
    @property
    def edad(self):
        return self.__edad

    @edad.setter
    def edad(self, valor):
        if valor > 18:
            self.__edad = valor
        else:
            raise ValueError("La edad debe ser mayor a 18")

    def __str__(self):
        return str(self.__dict__)
if __name__ == "__main__":
    mi_cliente = Cliente(
        "Carlos",
        "Lopez",
        "0912345678",
        "carlos@email.com",
        True,
        "Guayaquil",
        "042345678",
        "0991234567",
        30
    )

    print(mi_cliente)