# -*- coding: utf-8 -*-
"""TALLER 5/05/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Agtm7OXH8tSFo6-CV49ApY-QGX8XVLMR

FIGURA GEOMETRICAS
"""

class FiguraGeometrica:
    def __init__(self, alto, ancho):
        self.set_alto(alto)
        self.set_ancho(ancho)

    def __str__(self):
        return f"FiguraGeometrica(alto={self._alto}, ancho={self._ancho})"

    # GET y SET
    def get_alto(self):
        return self._alto

    def set_alto(self, alto):
        if alto > 0:
            self._alto = alto
        else:
            raise ValueError("El alto debe ser positivo")

    def get_ancho(self):
        return self._ancho

    def set_ancho(self, ancho):
        if ancho > 0:
            self._ancho = ancho
        else:
            raise ValueError("El ancho debe ser positivo")

    # PROPERTY
    @property
    def alto(self):
        return self._alto

    @alto.setter
    def alto(self, valor):
        self.set_alto(valor)

    @property
    def ancho(self):
        return self._ancho

    @ancho.setter
    def ancho(self, valor):
        self.set_ancho(valor)

"""COLOR"""

class Color:
    def __init__(self, color):
        self.set_color(color)

    def get_color(self):
        return self._color

    def set_color(self, color):
        if isinstance(color, str) and color.strip() != "":
            self._color = color
        else:
            raise ValueError("El color debe ser un texto válido")

    @property
    def color(self):
        return self._color

    @color.setter
    def color(self, valor):
        self.set_color(valor)

    def __str__(self):
        return f"Color: {self._color}"

"""RECTANGULO"""

class Rectangulo(FiguraGeometrica, Color):

    def __init__(self, alto, ancho, color):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self):
        return self.alto * self.ancho

    def __str__(self):
        return (f"Rectángulo -> alto: {self.alto}, ancho: {self.ancho}, "
                f"color: {self.color}, área: {self.area()}")

"""CUADRADO"""

class Cuadrado(FiguraGeometrica, Color):

    def __init__(self, lado, color):
        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    def area(self):
        return self.alto ** 2

    def __str__(self):
        return (f"Cuadrado -> lado: {self.alto}, "
                f"color: {self.color}, área: {self.area()}")

"""CIRCUNFERENCIA"""

import math

class Circunferencia(Color):

    def __init__(self, radio, color):
        super().__init__(color)
        self._radio = None
        self.set_radio(radio)

    def get_radio(self):
        return self._radio

    def set_radio(self, radio):
        if radio > 0:
            self._radio = radio
        else:
            raise ValueError("El radio debe ser positivo")

    @property
    def radio(self):
        return self._radio

    @radio.setter
    def radio(self, valor):
        self.set_radio(valor)

    def area(self):
        return math.pi * (self.radio ** 2)

    def __str__(self):
        return (f"Circunferencia -> radio: {self.radio}, "
                f"color: {self.color}, área: {self.area():.2f}")

import math

class Circunferencia(Color):

    def __init__(self, radio, color):
        super().__init__(color)
        self._radio = None
        self.set_radio(radio)

    def get_radio(self):
        return self._radio

    def set_radio(self, radio):
        if radio > 0:
            self._radio = radio
        else:
            raise ValueError("El radio debe ser positivo")

    @property
    def radio(self):
        return self._radio

    @radio.setter
    def radio(self, valor):
        self.set_radio(valor)

    def area(self):
        return math.pi * (self.radio ** 2)

    def __str__(self):
        return (f"Circunferencia -> radio: {self.radio}, "
                f"color: {self.color}, área: {self.area():.2f}")

if __name__ == "__main__":
    print("=== RECTÁNGULO ===")
    r = Rectangulo(10, 5, "rojo")
    print(r)

    print("\n=== CUADRADO ===")
    c = Cuadrado(4, "azul")
    print(c)

    print("\n=== CIRCUNFERENCIA ===")
    cir = Circunferencia(3, "verde")
    print(cir)

    # Prueba de setters
    r.alto = 20
    r.ancho = 10
    r.color = "amarillo"

    print("\nRectángulo modificado:")
    print(r)

"""PRUEBAS"""

if __name__ == "__main__":
    print("=== RECTÁNGULO ===")
    r = Rectangulo(10, 5, "rojo")
    print(r)

    print("\n=== CUADRADO ===")
    c = Cuadrado(4, "azul")
    print(c)

    print("\n=== CIRCUNFERENCIA ===")
    cir = Circunferencia(3, "verde")
    print(cir)

    # Prueba de setters
    r.alto = 20
    r.ancho = 10
    r.color = "amarillo"

    print("\nRectángulo modificado:")
    print(r)