# -*- coding: utf-8 -*-
"""Taller 6/05/52026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noVashSy80Lo6Vm-nbpjDtW3nQfobdCU
"""

"""
README - Figuras Geométricas

Este programa implementa clases usando herencia múltiple para representar
figuras geométricas con color.

Clases:
- FiguraGeometrica (base)
- Color
- Cuadrado
- Rectangulo
- Circunferencia

Funcionalidades:
- Cálculo de área
- Cálculo de perímetro
- Validación de datos (no negativos, no vacíos)
- Aplicación de polimorfismo mediante métodos compartidos.

Estudiante: [Tu Nombre]
Fecha: [06-05-2026]
"""

import math


class FiguraGeometrica:
    def __init__(self, alto: float, ancho: float):
        self.alto = alto
        self.ancho = ancho

    @property
    def alto(self):
        return self.__alto

    @alto.setter
    def alto(self, valor):
        if valor > 0:
            self.__alto = valor
        else:
            raise ValueError("El alto debe ser positivo")

    @property
    def ancho(self):
        return self.__ancho

    @ancho.setter
    def ancho(self, valor):
        if valor > 0:
            self.__ancho = valor
        else:
            raise ValueError("El ancho debe ser positivo")

    def __str__(self):
        return f"Figura geométrica -> Alto: {self.alto}, Ancho: {self.ancho}"


class Color:
    def __init__(self, color: str):
        self.color = color

    @property
    def color(self):
        return self._color

    @color.setter
    def color(self, valor):
        if valor and isinstance(valor, str):
            self._color = valor.strip()
        else:
            raise ValueError("El color no puede estar vacío")

    def __str__(self):
        return f"Color: {self._color}"


class Cuadrado(FiguraGeometrica, Color):

    def __init__(self, lado: float, color: str):
        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    def area(self):
        return self.alto ** 2

    def perimetro(self):
        return 4 * self.alto

    def __str__(self):
        return f"Cuadrado -> {FiguraGeometrica.__str__(self)}, {Color.__str__(self)}"


class Rectangulo(FiguraGeometrica, Color):

    def __init__(self, alto: float, ancho: float, color: str):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self):
        return self.alto * self.ancho

    def perimetro(self):
        return 2 * (self.alto + self.ancho)

    def __str__(self):
        return f"Rectángulo -> {FiguraGeometrica.__str__(self)}, {Color.__str__(self)}"


class Circunferencia(FiguraGeometrica, Color):

    def __init__(self, radio: float, color: str):
        FiguraGeometrica.__init__(self, radio, radio)
        Color.__init__(self, color)

    def area(self):
        return math.pi * (self.alto ** 2)

    def perimetro(self):
        return 2 * math.pi * self.alto

    def __str__(self):
        return f"Circunferencia -> Radio: {self.alto}, {Color.__str__(self)}"


# ---------------- PRUEBAS ----------------

if __name__ == "__main__":

    print(" --- PRUEBAS DE FIGURAS --- \n")

    # NUEVAS MEDIDAS Y COLORES
    cuadrado = Cuadrado(8, "Morado")
    print(cuadrado)
    print("Área:", round(cuadrado.area(), 2))
    print("Perímetro:", round(cuadrado.perimetro(), 2))
    print()

    rectangulo = Rectangulo(7, 10, "Naranja")
    print(rectangulo)
    print("Área:", round(rectangulo.area(), 2))
    print("Perímetro:", round(rectangulo.perimetro(), 2))
    print()

    circunferencia = Circunferencia(5, "Amarillo")
    print(circunferencia)
    print("Área:", round(circunferencia.area(), 2))
    print("Perímetro:", round(circunferencia.perimetro(), 2))


# ---------------- POLIMORFISMO ----------------

def sumar_areas(figuras_geometricas):
    suma_areas = 0

    for figura in figuras_geometricas:
        suma_areas += figura.area()

    return suma_areas


def sumar_perimetros(figuras_geometricas):
    suma_perimetros = 0

    for figura in figuras_geometricas:
        suma_perimetros += figura.perimetro()

    return suma_perimetros


print("\n --- POLIMORFISMO --- \n")

# Lista con diferentes objetos
figuras = [
    Cuadrado(8, "Morado"),
    Rectangulo(7, 10, "Naranja"),
    Circunferencia(5, "Amarillo")
]

# Mostrar cada figura
for figura in figuras:
    print(figura)
    print("Área:", round(figura.area(), 2))
    print("Perímetro:", round(figura.perimetro(), 2))
    print()

# Totales
print(" Suma total de áreas:", round(sumar_areas(figuras), 2))
print(" Suma total de perímetros:", round(sumar_perimetros(figuras), 2))